services:
  app:
    build: .
    ports:
      - "${PORT:-8081}:8081"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    stdin_open: true
    tty: true
    networks:
      - waza-network

networks:
  waza-network:
    driver: bridge
